layout_spectrum: 0
name: wubzalabs
author:
  name: Michael WB
  email: michael@wubza.com
title: Welcome to WubzaLabs
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
navigation:
  - id: 00d0962b-8ce5-4278-92f4-c52a20d0daa9
    name: First Post
    type: content
color:
  brandStrength: 0.5665240215603262
  saturation: 0.7115929799620062
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  lightness: 0.2770760839339346
  rhythmicContrast: 0.8342187826056033
typography_spectrum: 0.7168459
